import { createHash } from 'node:crypto';
import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { GAME_VERSION, VERSION_LOG } from '../src/data/version.js';

const rootDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const packagePath = path.join(rootDir, 'package.json');
const changelogPath = path.join(rootDir, 'CHANGELOG.md');
const standalonePath = path.join(rootDir, 'dist', 'standalone.html');
const manifestPath = path.join(rootDir, 'dist', 'release-manifest.json');

const packageJson = JSON.parse(await readFile(packagePath, 'utf8'));
const changelog = await readFile(changelogPath, 'utf8');
const standalone = await readFile(standalonePath);
const standaloneText = standalone.toString('utf8');
const changelogVersion = changelog.match(/^## v([^\s]+)\s+-/m)?.[1];
const requestedTag = readTagArgument(process.argv.slice(2));

assertVersion('package.json', packageJson.version, GAME_VERSION);
assertVersion('VERSION_LOG', VERSION_LOG[0]?.ver, GAME_VERSION);
assertVersion('CHANGELOG.md', changelogVersion, GAME_VERSION);
if (requestedTag) assertVersion('release tag', requestedTag, GAME_VERSION);

assertStandalone(standaloneText);

const manifest = {
  name: packageJson.name,
  version: GAME_VERSION,
  file: 'standalone.html',
  bytes: standalone.byteLength,
  sha256: createHash('sha256').update(standalone).digest('hex'),
};
await writeFile(manifestPath, `${JSON.stringify(manifest, null, 2)}\n`, 'utf8');

console.log(`release verified: v${GAME_VERSION} · ${manifest.bytes} bytes · sha256 ${manifest.sha256}`);

function assertVersion(source, actual, expected) {
  if (normalizeVersion(actual) !== normalizeVersion(expected)) {
    throw new Error(`${source} version ${actual ?? '(missing)'} does not match GAME_VERSION ${expected}`);
  }
}

function normalizeVersion(version) {
  const value = String(version || '').replace(/^v/, '');
  if (!/^\d+\.\d+(?:\.\d+)?$/.test(value)) throw new Error(`Invalid version: ${version ?? '(missing)'}`);
  return value.replace(/\.0$/, '');
}

function readTagArgument(args) {
  const index = args.indexOf('--tag');
  if (index === -1) return null;
  if (!args[index + 1]) throw new Error('--tag requires a value');
  return args[index + 1];
}

function assertStandalone(html) {
  const checks = [
    [/Generated by scripts\/build-standalone\.mjs/, 'generated standalone marker'],
    [/<style>[\s\S]+<\/style>/, 'inlined stylesheet'],
    [/<script type="module">[\s\S]+<\/script>/, 'inlined module script'],
  ];
  checks.forEach(([pattern, label]) => {
    if (!pattern.test(html)) throw new Error(`Standalone is missing ${label}`);
  });
  const unresolved = [
    /<script\b[^>]*\bsrc\s*=/i,
    /<link\b(?=[^>]*\brel=["']stylesheet["'])(?=[^>]*\bhref\s*=)/i,
    /<(?:img|source|video|audio)\b[^>]*\bsrc=["'](?!data:)/i,
    /(?:src|href)=["']\.?\/?assets\//i,
    /(?:url\(|["'])\.\/?data:/i,
  ];
  if (unresolved.some((pattern) => pattern.test(html))) {
    throw new Error('Standalone still contains an external asset reference');
  }
}
